name: Compile Reports
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/compile.yml' # Ensures changes to this file also trigger this workflow.
      - 'reports/*' # Only file changes in reports directory triggers this workflow.
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: git lfs install

      - name: Pull LFS objects
        run: git lfs pull

      - name: Compile LaTeX document
        # Using https://github.com/xu-cheng/latex-action
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ./reports/Nora_SURF_Proposal.tex
            ./reports/Tanisha_SURF_Proposal.tex
            ./reports/Tanisha_SURF_Report.tex
          work_in_root_file_dir: True
        # Change filename above if different.
        # Use following to compile multiple latex files
        # with:
        #   root_file: |
        #     file1.tex
        #     file2.tex
      - name: List compiled PDFs
        run: ls -l ./reports/
  
      - name: Create published directory
        run: |
          mkdir ./public
          cp ./reports/Nora_SURF_Proposal.pdf ./public/
          cp ./reports/Tanisha_SURF_Proposal.pdf ./public/
          cp ./reports/Tanisha_SURF_Report.pdf ./public/
        # Add more files above to publish them if required.
      - name: Upload latest compiled output to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
